apiVersion: v1
kind: Service
metadata:
  name: netflix-app-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: netflix-app
