apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:

  - name: simple-page-nginx

    newName: 443628962956.dkr.ecr.us-east-1.amazonaws.com/simple-page-nginx

    newTag: latest